# Generated by Django 5.2.7 on 2025-10-26 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('video', models.URLField()),
                ('upload_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
