# Generated by Django 5.2.7 on 2025-10-26 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='video',
            field=models.FileField(upload_to='video/'),
        ),
    ]
